# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20170330_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='correctChoice',
            field=models.CharField(choices=[(0, 'а)'), (1, 'б)'), (2, 'в)'), (3, 'г)')], max_length=128, verbose_name='Правильна відповідь:'),
        ),
    ]
