# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20170330_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='correctChoice',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 10), (2, 20), (3, 30)], verbose_name='Правильна відповідь:'),
        ),
    ]
