# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20170330_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='condition',
            field=models.TextField(max_length=512, null=True, verbose_name='Умова завдання'),
        ),
        migrations.AlterField(
            model_name='test',
            name='correctChoice',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Варіант а)'), (1, 'Варіант б)'), (2, 'Варіант в)'), (3, 'Варіант г)')], null=True, verbose_name='Правильна відповідь:'),
        ),
        migrations.AlterField(
            model_name='test',
            name='first',
            field=models.CharField(max_length=128, null=True, verbose_name='а) :'),
        ),
        migrations.AlterField(
            model_name='test',
            name='fourth',
            field=models.CharField(max_length=128, null=True, verbose_name='г) :'),
        ),
        migrations.AlterField(
            model_name='test',
            name='second',
            field=models.CharField(max_length=128, null=True, verbose_name='б) :'),
        ),
        migrations.AlterField(
            model_name='test',
            name='third',
            field=models.CharField(max_length=128, null=True, verbose_name='в) :'),
        ),
    ]
